### ISSUE TITLE
Unable to upload new Android apk

### ISSUE THREAD

**Issue by bidsinga** [cycleplanet/cycle-planet#106]
Does anyone have experience with signing app for android, using cordova? I used to be able to generate an apk file which could be uploaded to Google Play, but the signing method has changed recently and now I'm unable to sign. Google Play throws an error `You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme` . I used to use jarsigner, but now have to use apksigner, which I'm trying to use in the developing terminal, but also throws an error saying `apksigner : The term 'apksigner' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

**Comment by jphillips05** [comment]
The android SDK target needs to be 30. You need at least the cordova android 10 library

**Comment by jphillips05** [comment]
the cordova stuff isnt checked into the project but you should be able to follow this: https://quasar.dev/quasar-cli/developing-cordova-apps/preparation

but when you add android specify 10
cordova platform add android@10.0.1

**Comment by reinierl** [comment]
I set up the Android development environment on my machine now and the app runs in the emulator. With the problematic Android SDK 30 even it seems. So once I get access to the Google Play Developer Account releasing the app shouldn't be a big deal, normally speaking.

**Comment by bidsinga** [comment]
Signing has now been succesfull. It appeared we had to update android as mentioned by @jphillips05, and we also had to remove a few deprecated cordova plugins.
