### ISSUE TITLE
slow loading of loadPoiByIds 

### ISSUE THREAD

**Issue by bidsinga** [cycleplanet/cycle-planet#88]
The `loadPoiByIds` fetches POI's by an array of given keys, and loops through it with a `for` loop. When you pass more than i.g. 100 keys, loading time can take up to a minute. 

See also 
_Originally posted by @reinierl in https://github.com/cycleplanet/cycle-planet/issues/87#issuecomment-940745928_

**Comment by reinierl** [comment]
@bidsinga Did you check if this makes things faster for you? I was too lazy unfortunately to set up my own DB with 100s of markers to test... :)
