### ISSUE TITLE
Give ModalUsername, ModalUsername2 etc descriptive names

### ISSUE THREAD

**Issue by reinierl** [cycleplanet/cycle-planet#95]
At the moment we have no less than four Vue components named "ModalUsername":

[ModalUsername](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/ModalUsername.vue)
[ModalUsername2](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/ModalUsername2.vue)
[ModalUsername3](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/ModalUsername3.vue)
[ModalUsername4](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/ModalUsername4.vue)

These have to be given better names that describe the differences between them. Also we should check if in fact some of them can be combined into one component that can be parameterised for the desired behaviour or looks.

**Comment by bidsinga** [comment]
ModalUsername renamed to UsernameNoAvatar
ModalUsername2 renamed to UsernameAvatar
ModalUsername3 renamed to UsernameAvatarChip
removed ModalUsername4
