### ISSUE TITLE
Give ModalCountryChip, ModalCountryChip2 etc descriptive names

### ISSUE THREAD

**Issue by reinierl** [cycleplanet/cycle-planet#96]
At the moment we have no less than four Vue components named "ModalCountryChip":

[ModalCountryChip](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/ModalCountryChip.vue)
[ModalCountryChip2](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/ModalCountryChip2.vue)
[ModalCountryChip3](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/ModalCountryChip3.vue)
[ModalCountryChip4](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/ModalCountryChip4.vue)

These have to be given better names that describe the differences between them. Also we should check if in fact some of them can be combined into one component that can be parameterised for the desired behaviour or looks.

**Comment by bidsinga** [comment]
ModalCountryChip renamed to CountrychipLarge
ModalCountryChip2 renamed to CountrychipSmall
removed ModalCountryChip3
removed ModalCountryChip4
