### ISSUE TITLE
Give NiceDate and NiceDate2 descriptive names

### ISSUE THREAD

**Issue by reinierl** [cycleplanet/cycle-planet#97]
At the moment we have two Vue components named "NiceDate":

[NiceDate](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/NiceDate.vue)
[NiceDate2](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/Modals/NiceDate2.vue)

These have to be given better names that describe the differences between them. Also we should check if in fact they can be combined into one component that can be parameterised for the desired behaviour or looks.

**Comment by bidsinga** [comment]
`NiceDate `renamed to `DateDifference`
NiceDate2 renamed to `DateCreated`
