### ISSUE TITLE
Give MapMarker and MapMarker2 descriptive names

### ISSUE THREAD

**Issue by reinierl** [cycleplanet/cycle-planet#98]
At the moment wetwo Vue components named "MapMarker":

[MapMarker](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/MapMarker.vue)
[MapMarker2](https://github.com/cycleplanet/cycle-planet/tree/main/src/components/Shared/MapMarker2.vue)

These have to be given better names that describe the differences between them. Also we should check if in fact they can be combined into one component that can be parameterised for the desired behaviour or looks.

**Comment by bidsinga** [comment]
`MapMarker `is moved to `componentns/Country` folder and renamed to `CountryPOIs`
`MapMarker2 `is renamed to `POIList`
